[2023-06-01T11:14:02.154+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2023-06-01T11:14:00.183542+00:00 [queued]>
[2023-06-01T11:14:02.189+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2023-06-01T11:14:00.183542+00:00 [queued]>
[2023-06-01T11:14:02.195+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-01T11:14:02.197+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-06-01T11:14:02.198+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-01T11:14:02.279+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-06-01 11:14:00.183542+00:00
[2023-06-01T11:14:02.307+0000] {standard_task_runner.py:55} INFO - Started process 100 to run task
[2023-06-01T11:14:02.311+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'create_postgres_table', 'manual__2023-06-01T11:14:00.183542+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/postgres.py', '--cfg-path', '/tmp/tmp53g8zf70']
[2023-06-01T11:14:02.316+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask create_postgres_table
[2023-06-01T11:14:02.666+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2023-06-01T11:14:00.183542+00:00 [running]> on host 687ba427e841
[2023-06-01T11:14:03.036+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v03
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-01T11:14:00.183542+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-01T11:14:00.183542+00:00
[2023-06-01T11:14:03.038+0000] {sql.py:253} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-06-01T11:14:03.063+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-01T11:14:04.283+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-01T11:14:14.309+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 331, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Temporary failure in name resolution

[2023-06-01T11:14:14.322+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v03, task_id=create_postgres_table, execution_date=20230601T111400, start_date=20230601T111402, end_date=20230601T111414
[2023-06-01T11:14:14.340+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task create_postgres_table (could not translate host name "host.docker.local" to address: Temporary failure in name resolution
; 100)
[2023-06-01T11:14:14.370+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-01T11:14:14.404+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
