[2023-06-01T10:34:32.779+0000] {processor.py:153} INFO - Started process (PID=49) to work on /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:34:32.783+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/monitorDAG.py for tasks to queue
[2023-06-01T10:34:32.786+0000] {logging_mixin.py:137} INFO - [2023-06-01T10:34:32.785+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:34:32.855+0000] {logging_mixin.py:137} INFO - [2023-06-01T10:34:32.849+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/monitorDAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/monitorDAG.py", line 34, in <module>
    for dag_id in fetch_dags.output:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 251, in __iter__
    raise TypeError("'XComArg' object is not iterable")
TypeError: 'XComArg' object is not iterable
[2023-06-01T10:34:32.857+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:34:32.890+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/monitorDAG.py took 0.117 seconds
[2023-06-01T10:35:03.268+0000] {processor.py:153} INFO - Started process (PID=80) to work on /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:35:03.272+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/monitorDAG.py for tasks to queue
[2023-06-01T10:35:03.275+0000] {logging_mixin.py:137} INFO - [2023-06-01T10:35:03.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:35:03.374+0000] {logging_mixin.py:137} INFO - [2023-06-01T10:35:03.369+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/monitorDAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/monitorDAG.py", line 34, in <module>
    for dag_id in fetch_dags.output:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 251, in __iter__
    raise TypeError("'XComArg' object is not iterable")
TypeError: 'XComArg' object is not iterable
[2023-06-01T10:35:03.376+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:35:03.431+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/monitorDAG.py took 0.173 seconds
[2023-06-01T10:35:33.855+0000] {processor.py:153} INFO - Started process (PID=110) to work on /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:35:33.859+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/monitorDAG.py for tasks to queue
[2023-06-01T10:35:33.863+0000] {logging_mixin.py:137} INFO - [2023-06-01T10:35:33.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:35:33.927+0000] {logging_mixin.py:137} INFO - [2023-06-01T10:35:33.924+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/monitorDAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/monitorDAG.py", line 34, in <module>
    for dag_id in fetch_dags.output:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 251, in __iter__
    raise TypeError("'XComArg' object is not iterable")
TypeError: 'XComArg' object is not iterable
[2023-06-01T10:35:33.931+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:35:33.968+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/monitorDAG.py took 0.124 seconds
[2023-06-01T10:36:04.336+0000] {processor.py:153} INFO - Started process (PID=141) to work on /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:36:04.339+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/monitorDAG.py for tasks to queue
[2023-06-01T10:36:04.342+0000] {logging_mixin.py:137} INFO - [2023-06-01T10:36:04.341+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:36:04.417+0000] {logging_mixin.py:137} INFO - [2023-06-01T10:36:04.415+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/monitorDAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/monitorDAG.py", line 34, in <module>
    for dag_id in fetch_dags.output:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 251, in __iter__
    raise TypeError("'XComArg' object is not iterable")
TypeError: 'XComArg' object is not iterable
[2023-06-01T10:36:04.419+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/monitorDAG.py
[2023-06-01T10:36:04.449+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/monitorDAG.py took 0.119 seconds
